import { Job, Candidate, Interview, Feedback } from './types';

export const PROCESS_STAGES = ['Applied', 'Shortlisted', 'Interview', 'Offer', 'Hired', 'Rejected'];

export const mockJobs: Job[] = [
    {
        id: '1',
        title: 'Senior Frontend Engineer',
        department: 'Engineering',
        location: 'Remote',
        type: 'Full-time',
        status: 'Published',
        salaryRange: '$120k - $160k',
        description: 'We are looking for an experienced Frontend Engineer to lead our core product team.',
        requirements: ['5+ years React', 'TypeScript', 'TailwindCSS', 'System Design'],
        experienceLevel: 'Senior',
        applicantsCount: 14,
        postedDate: '2023-10-15',
    },
    {
        id: '2',
        title: 'Product Designer',
        department: 'Design',
        location: 'New York, NY',
        type: 'Full-time',
        status: 'Published',
        salaryRange: '$100k - $140k',
        description: 'Join our design team to craft beautiful user experiences.',
        requirements: ['Figma', 'Prototyping', 'User Research'],
        experienceLevel: 'Mid-Level',
        applicantsCount: 8,
        postedDate: '2023-10-20',
    },
    {
        id: '3',
        title: 'Marketing Manager',
        department: 'Marketing',
        location: 'London, UK',
        type: 'Full-time',
        status: 'Draft',
        salaryRange: '£60k - £80k',
        description: 'Lead our growth marketing initiatives.',
        requirements: ['SEO', 'Content Strategy', 'Analytics'],
        experienceLevel: 'Mid-Level',
        applicantsCount: 0,
        postedDate: '2023-11-01',
    },
    {
        id: '4',
        title: 'Backend Developer',
        department: 'Engineering',
        location: 'San Francisco, CA',
        type: 'Contract',
        status: 'Closed',
        salaryRange: '$80/hr',
        description: 'Help us migrate our legacy API.',
        requirements: ['Node.js', 'PostgreSQL', 'AWS'],
        experienceLevel: 'Senior',
        applicantsCount: 45,
        postedDate: '2023-09-10',
    },
];

export const mockCandidates: Candidate[] = [
    {
        id: 'c1',
        name: 'Sarah Jenkins',
        role: 'Senior Frontend Engineer',
        email: 'sarah.j@example.com',
        phone: '+1 555-0123',
        stage: 'Interview',
        resumeLink: '#',
        appliedDate: '2023-10-18',
        notes: 'Strong React skills, good communication.',
    },
    {
        id: 'c2',
        name: 'Michael Chen',
        role: 'Senior Frontend Engineer',
        email: 'm.chen@example.com',
        phone: '+1 555-0124',
        stage: 'Applied',
        resumeLink: '#',
        appliedDate: '2023-10-25',
    },
    {
        id: 'c3',
        name: 'Jessica Dubost',
        role: 'Product Designer',
        email: 'j.dubost@example.com',
        phone: '+33 6 12 34 56 78',
        stage: 'Shortlisted',
        resumeLink: '#',
        appliedDate: '2023-10-22',
    },
    {
        id: 'c4',
        name: 'David Kim',
        role: 'Backend Developer',
        email: 'd.kim@example.com',
        phone: '+1 555-9876',
        stage: 'Offer',
        resumeLink: '#',
        appliedDate: '2023-09-15',
    },
    {
        id: 'c5',
        name: 'Emily Davis',
        role: 'Product Designer',
        email: 'emily.d@example.com',
        phone: '+1 555-4321',
        stage: 'Rejected',
        resumeLink: '#',
        appliedDate: '2023-10-21',
    },
];

export const mockInterviews: Interview[] = [
    {
        id: 'i1',
        candidateId: 'c1',
        candidateName: 'Sarah Jenkins',
        interviewer: 'Alex Rivera',
        date: '2023-11-15',
        time: '14:00',
        mode: 'Online',
        meetingLink: 'https://meet.google.com/abc-defg-hij',
        status: 'Scheduled',
    },
    {
        id: 'i2',
        candidateId: 'c3',
        candidateName: 'Jessica Dubost',
        interviewer: 'Maria Garcia',
        date: '2023-11-16',
        time: '10:30',
        mode: 'Online',
        meetingLink: 'https://meet.google.com/xyz-uvw-lmn',
        status: 'Scheduled',
    },
];
